/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HalalRouteImport } from './routes/halal'
import { Route as MosquesRouteImport } from './routes/mosques'
import { Route as NamesRouteImport } from './routes/names'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as PrayersRouteImport } from './routes/prayers'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as TasbihRouteImport } from './routes/tasbih'
import { Route as InvocationsCatRouteImport } from './routes/invocations/$cat'
import { Route as ReminderAudioRouteImport } from './routes/reminder/audio'
import { Route as ReminderComboRouteImport } from './routes/reminder/combo'
import { Route as ReminderNotificationRouteImport } from './routes/reminder/notification'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HalalRoute = HalalRouteImport.update({
  id: '/halal',
  path: '/halal',
  getParentRoute: () => rootRouteImport,
} as any)
const MosquesRoute = MosquesRouteImport.update({
  id: '/mosques',
  path: '/mosques',
  getParentRoute: () => rootRouteImport,
} as any)
const NamesRoute = NamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayersRoute = PrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const InvocationsCatRoute = InvocationsCatRouteImport.update({
  id: '/invocations/$cat',
  path: '/invocations/$cat',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderAudioRoute = ReminderAudioRouteImport.update({
  id: '/reminder/audio',
  path: '/reminder/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderComboRoute = ReminderComboRouteImport.update({
  id: '/reminder/combo',
  path: '/reminder/combo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReminderNotificationRoute = ReminderNotificationRouteImport.update({
  id: '/reminder/notification',
  path: '/reminder/notification',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/halal': typeof HalalRoute
  '/mosques': typeof MosquesRoute
  '/names': typeof NamesRoute
  '/permissions': typeof PermissionsRoute
  '/prayers': typeof PrayersRoute
  '/quran': typeof QuranRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/tasbih': typeof TasbihRoute
  '/invocations/$cat': typeof InvocationsCatRoute
  '/reminder/audio': typeof ReminderAudioRoute
  '/reminder/combo': typeof ReminderComboRoute
  '/reminder/notification': typeof ReminderNotificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/halal': typeof HalalRoute
  '/mosques': typeof MosquesRoute
  '/names': typeof NamesRoute
  '/permissions': typeof PermissionsRoute
  '/prayers': typeof PrayersRoute
  '/quran': typeof QuranRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/tasbih': typeof TasbihRoute
  '/invocations/$cat': typeof InvocationsCatRoute
  '/reminder/audio': typeof ReminderAudioRoute
  '/reminder/combo': typeof ReminderComboRoute
  '/reminder/notification': typeof ReminderNotificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/halal': typeof HalalRoute
  '/mosques': typeof MosquesRoute
  '/names': typeof NamesRoute
  '/permissions': typeof PermissionsRoute
  '/prayers': typeof PrayersRoute
  '/quran': typeof QuranRoute
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
  '/tasbih': typeof TasbihRoute
  '/invocations/$cat': typeof InvocationsCatRoute
  '/reminder/audio': typeof ReminderAudioRoute
  '/reminder/combo': typeof ReminderComboRoute
  '/reminder/notification': typeof ReminderNotificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/halal'
    | '/mosques'
    | '/names'
    | '/permissions'
    | '/prayers'
    | '/quran'
    | '/settings'
    | '/splash'
    | '/tasbih'
    | '/invocations/$cat'
    | '/reminder/audio'
    | '/reminder/combo'
    | '/reminder/notification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/halal'
    | '/mosques'
    | '/names'
    | '/permissions'
    | '/prayers'
    | '/quran'
    | '/settings'
    | '/splash'
    | '/tasbih'
    | '/invocations/$cat'
    | '/reminder/audio'
    | '/reminder/combo'
    | '/reminder/notification'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/halal'
    | '/mosques'
    | '/names'
    | '/permissions'
    | '/prayers'
    | '/quran'
    | '/settings'
    | '/splash'
    | '/tasbih'
    | '/invocations/$cat'
    | '/reminder/audio'
    | '/reminder/combo'
    | '/reminder/notification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  HalalRoute: typeof HalalRoute
  MosquesRoute: typeof MosquesRoute
  NamesRoute: typeof NamesRoute
  PermissionsRoute: typeof PermissionsRoute
  PrayersRoute: typeof PrayersRoute
  QuranRoute: typeof QuranRoute
  SettingsRoute: typeof SettingsRoute
  SplashRoute: typeof SplashRoute
  TasbihRoute: typeof TasbihRoute
  InvocationsCatRoute: typeof InvocationsCatRoute
  ReminderAudioRoute: typeof ReminderAudioRoute
  ReminderComboRoute: typeof ReminderComboRoute
  ReminderNotificationRoute: typeof ReminderNotificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halal': {
      id: '/halal'
      path: '/halal'
      fullPath: '/halal'
      preLoaderRoute: typeof HalalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosques': {
      id: '/mosques'
      path: '/mosques'
      fullPath: '/mosques'
      preLoaderRoute: typeof MosquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/names': {
      id: '/names'
      path: '/names'
      fullPath: '/names'
      preLoaderRoute: typeof NamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayers': {
      id: '/prayers'
      path: '/prayers'
      fullPath: '/prayers'
      preLoaderRoute: typeof PrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invocations/$cat': {
      id: '/invocations/$cat'
      path: '/invocations/$cat'
      fullPath: '/invocations/$cat'
      preLoaderRoute: typeof InvocationsCatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder/audio': {
      id: '/reminder/audio'
      path: '/reminder/audio'
      fullPath: '/reminder/audio'
      preLoaderRoute: typeof ReminderAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder/combo': {
      id: '/reminder/combo'
      path: '/reminder/combo'
      fullPath: '/reminder/combo'
      preLoaderRoute: typeof ReminderComboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminder/notification': {
      id: '/reminder/notification'
      path: '/reminder/notification'
      fullPath: '/reminder/notification'
      preLoaderRoute: typeof ReminderNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  HalalRoute: HalalRoute,
  MosquesRoute: MosquesRoute,
  NamesRoute: NamesRoute,
  PermissionsRoute: PermissionsRoute,
  PrayersRoute: PrayersRoute,
  QuranRoute: QuranRoute,
  SettingsRoute: SettingsRoute,
  SplashRoute: SplashRoute,
  TasbihRoute: TasbihRoute,
  InvocationsCatRoute: InvocationsCatRoute,
  ReminderAudioRoute: ReminderAudioRoute,
  ReminderComboRoute: ReminderComboRoute,
  ReminderNotificationRoute: ReminderNotificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
